name: 'Release Milestone Check'
on:
  pull_request_target:
    types:
    - opened
    - reopened
    - synchronize

jobs:
  check-release-milestone:
    name: Check if release milestone exists
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        path: './'  

    - id: version
      run: |
        version=`cat ./VERSION`
        echo "::set-output name=version::$version"

    - name: Block merge if milestone is missing
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const version = '${{ steps.version.outputs.version }}';
          const nextMinorRegex = /^(v[0-9]+\.[0-9]+)\.0-dev/gmi;

          let match = nextMinorRegex.exec(version);
          if (match == null) {
            core.info('VERSION does not indicate that the next version is a new minor release');
            return;
          }
          const nextMinorVersion = match[1];
          
          // TODO
          core.info(version);
          core.info(nextMinorVersion);

          const milestones = await github.issues.listMilestones({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            sort: 'due_on',
            direction: 'desc'
          });
          
          console.log(context);
          console.log(context.issue);
          console.log(context.issue.milestone);
          console.log(context.payload.pull_request.milestone);
      
          for (const milestone of milestones.data) {
            core.info("processing " + milestone.title);
            if (milestone.title != nextMinorVersion) {
              core.info("skipping");
              continue;
            }

            // milestone found, check if PR is associated
            if (context.issue.milestone == null || context.issue.milestone.title == null) {
              core.setFailed('milestone missing - cannot merge');
              return
            }
          }

          core.info('milestone not found - can merge');
